### PR TITLE
State management

### PR DESCRIPTION
**Pull request by whamester**
https://app.clickup.com/t/86b0hyyeb

Note:
This store is not meant to replace useState or local variables, is only meant to save the information we want to persist and share with several component levels.

https://github.com/LangaraBeetles/beetles-mobile/assets/57273227/9674241e-f549-492e-ac3e-b0376fa24c33

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b0hyyeb State with Zustand](https://app.clickup.com/t/86b0hyyeb)

**Review by ReinhardtBotha — APPROVED** [review]
nice! ✅

**Review by zeckkimon — APPROVED** [review]

**Comment by zeckkimon** [comment]
Task linked: [CU-86b0k8wr8 Navigation](https://app.clickup.com/t/86b0k8wr8)

**Review by Victorportus — APPROVED** [review]
Works in both samsung mobile and ipad

**Review by zeckkimon — APPROVED** [review]

**Pull request merged**
