### PR TITLE
CU 86b1n0qgb: Update streak screen

### PR DESCRIPTION
**Pull request by zeckkimon**
**Fix:**
* Added padding between flame and number.
* Changed confetti animation

**Not changed:**
* Change this screen to fade instead of slide in --> This is already implemented

https://github.com/user-attachments/assets/8d50b82c-8fca-4b6a-9018-8734035b4706

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b1n0qgb Update streak screen](https://app.clickup.com/t/86b1n0qgb)

**Review by whamester — APPROVED** [review]

**Comment by poojachauhan001** [comment]
1. The fire animation should not stop before the confetti finishes.

2. The confetti should be near the upper part of the screen

3. Y position of elements seems a bit off as compared to the design - https://www.figma.com/proto/PPygQ4sRjPUHr2hBe7aHxe/Updated-Mockups?page-id=0%3A1&node-id=2097-4474&viewport=-777%2C395%2C0.17&t=uUo6pGgwskialsm7-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1041%3A1784&show-proto-sidebar=1

@zeckkimon @whamester

**Review by ReinhardtBotha — APPROVED** [review]

**Comment by zeckkimon** [comment]
> 1. The fire animation should not stop before the confetti finishes.
> 2. The confetti should be near the upper part of the screen
> 3. Y position of elements seems a bit off as compared to the design - https://www.figma.com/proto/PPygQ4sRjPUHr2hBe7aHxe/Updated-Mockups?page-id=0%3A1&node-id=2097-4474&viewport=-777%2C395%2C0.17&t=uUo6pGgwskialsm7-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1041%3A1784&show-proto-sidebar=1
> 
> @zeckkimon @whamester

Hello @poojachauhan001. Noted on item 1. Please see below:

https://github.com/user-attachments/assets/49537bd0-33a4-452b-bfd9-464900470335



For the layout (items 2 and 3), I believe it's because I am using Android. May we please check the if the layout is good on 
 iOS @Victorportus or @whamester?

**Review by Victorportus — APPROVED** [review]

**Comment by poojachauhan001** [comment]
@zeckkimon Approved for item 1

**Comment by whamester** [comment]
@zeckkimon  Hi,

I also notice on your videos that the layout is off even for android, we have to check the vertical spacing.
Screenshot 2024-08-13 at 7 59 32 PM

**Review by whamester — CHANGES_REQUESTED** [review]
review vertical spacing

**Comment by Victorportus** [comment]
> > 1. The fire animation should not stop before the confetti finishes.
> > 2. The confetti should be near the upper part of the screen
> > 3. Y position of elements seems a bit off as compared to the design - https://www.figma.com/proto/PPygQ4sRjPUHr2hBe7aHxe/Updated-Mockups?page-id=0%3A1&node-id=2097-4474&viewport=-777%2C395%2C0.17&t=uUo6pGgwskialsm7-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1041%3A1784&show-proto-sidebar=1
> > 
> > @zeckkimon @whamester
> 
> Hello @poojachauhan001. Noted on item 1. Please see below:
> 
>  screen-20240813-115238.mp4 
> For the layout (items 2 and 3), I believe it's because I am using Android. May we please check the if the layout is good on iOS @Victorportus or @whamester?

I can't check it on the emulator, i can't get into the streak page, i only can check on my phone, also android

**Comment by zeckkimon** [comment]
I fixed the layout on Android. Please review if this is ok 😄 @whamester @poojachauhan001 

https://github.com/user-attachments/assets/0df3b06f-8103-4d7d-afda-4750c288fa9b

**Review by whamester — APPROVED** [review]

**Pull request merged**
