### PR TITLE
feat: setup pages structure

### PR DESCRIPTION
**Pull request by whamester**
🎉  Some new pages here

The basic structure for the setup pages and some cool animation there.

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b0kyhau Setup Screen](https://app.clickup.com/t/86b0kyhau)

**Review by ReinhardtBotha — APPROVED** [review]
👏

**Review by Victorportus — APPROVED** [review]
Nice!

**Review by zeckkimon — APPROVED** [review]
Look great!

**Pull request merged**
