### PR TITLE
Cu 86b1bjt44 onboarding pages

### PR DESCRIPTION
**Pull request by Victorportus**
https://www.figma.com/proto/PPygQ4sRjPUHr2hBe7aHxe/Updated-Mockups?node-id=1648-2462&m=dev&scaling=scale-down&content-scaling=fixed&page-id=1522%3A2648&starting-point-node-id=1648%3A2438&show-proto-sidebar=1

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b1bjt44 Onboarding Pages](https://app.clickup.com/t/86b1bjt44)

**Review by zeckkimon — APPROVED** [review]
This is awesome!

On Android, the Goal Picker decreased in height on Create Challenge, and Set Goal on Profile page.

**Review by whamester — APPROVED** [review]

**Review by whamester — CHANGES_REQUESTED** [review]
I'll post a file with the feedback

**Comment by whamester** [comment]
hi @Victorportus  would you check that the navigation components are placed consistently on all the onboarding screens?

https://www.figma.com/board/VEW2N3gYtt0tlZKcKFfMEI/System-Architecture?node-id=570-9146&t=uAo6I7Db2jB5TXA9-0
I've highlighted the sections where the back button and the CTAs are placed

**Comment by whamester** [comment]
Simulator Screenshot - iPhone 15 Pro - 2024-08-06 at 17 24 15
 let's fix the width of the button, if we need a different image, let's ask design for the asset

**Review by ReinhardtBotha — APPROVED** [review]

**Review by whamester — APPROVED** [review]

**Pull request merged**
