### PR TITLE
Cu 86b0qfeny button component

### PR DESCRIPTION
**Pull request by Victorportus**
Added the style for the buttons.

There are 4 options of buttons, the main differences are the color and the size. when calling a button needs 3 pops.

      <Button title="Clear name" onPress={onNameClear} type={{type: "secondary", size:"l"}}></Button>
      
title = label on button
onPress = functionality
type = object with 2 stings 
            type = "primary" or "secondary"
            size = "s" or "l"

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b0qfeny Button Component](https://app.clickup.com/t/86b0qfeny)

**Comment by Victorportus** [comment]
I also added the color from the figma file into the global styles

**Review by ReinhardtBotha — CHANGES_REQUESTED** [review]
just delete the ios folder in your local branch, then add `ios/` in the gitignore file and push your changes again so that it is not included in the PR

**Comment by Victorportus** [comment]
@ReinhardtBotha  The changes have been done as requested.

**Review by ReinhardtBotha — APPROVED** [review]

**Review by whamester — APPROVED** [review]

**Review by zeckkimon — APPROVED** [review]

**Pull request merged**
