### PR TITLE
Cu 86b11cm0w home page UI  session UI

### PR DESCRIPTION
**Pull request by Victorportus**
Final layout for the home screen and the session flow.

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b11cm0w Home Page UI / Session UI](https://app.clickup.com/t/86b11cm0w)

**Comment by ReinhardtBotha** [comment]
Those are a lot of commits! 
WilljOprahGIF

**Review by ReinhardtBotha — CHANGES_REQUESTED** [review]
If I click start session on my phone or emulator it just crashes with this following error:

Your app just crashed. See the error below.
java.lang.ArithmeticException: divide by zero
  com.aigestudio.wheelpicker.WheelPicker.onDraw(WheelPicker.java:545)

**Comment by ReinhardtBotha** [comment]
There are also a couple of styling issues in this branch:
image
image
image

**Review by zeckkimon — APPROVED** [review]
Approved for now. It doesn't break on my end. As discussed, let's address the issues in the next PR(s). 😄 

Some findings while testing using Android (Not sure if these are just Android-related issues):
* No reading is done during session, so empty record is being sent to the API which causes error 400. 

* Floating number 1 on the session duration modal 
image

**Review by ReinhardtBotha — APPROVED** [review]

**Pull request merged**
