### PR TITLE
feat: TrackingModeProvider

### PR DESCRIPTION
**Pull request by whamester**
Mode provider added for ios devices, the default mode is 'PHONE', the provider is responsible for updating the mode value with the defined callbacks, the mode value should be accessed with useUser 

Screenshot 2024-06-05 at 10 47 22 PM

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b0k6ezf AirPods - Bridging your react native application with iOS](https://app.clickup.com/t/86b0k6ezf)
Task linked: [CU-86b0qf65y Tracking Mode](https://app.clickup.com/t/86b0qf65y)

**Review by zeckkimon — APPROVED** [review]
Looks good!

**Review by ReinhardtBotha — COMMENTED** [review]
I'm getting an error trying to run this on Android: 
WhatsApp Image 2024-06-06 at 15 12 40_1dda9a54

**Review by Victorportus — APPROVED** [review]

**Review by ReinhardtBotha — APPROVED** [review]
✅

**Pull request merged**
