### PR TITLE
CU-86b15rqw2_Setup Set Daily Goal

### PR DESCRIPTION
**Pull request by zeckkimon**
**Includes:**
* GoalPicker
* Implement GoalPicker on Set Daily Goal page on setup

**To do:**
image

### CODE REVIEW

**Comment by zeckkimon** [comment]
Task linked: [CU-86b15rqw2 Setup - Set Daily Goal](https://app.clickup.com/t/86b15rqw2)

**Review by ReinhardtBotha — APPROVED** [review]
This looks great!! 👏🔥

**Review by Victorportus — APPROVED** [review]
Screenshot 2024-07-10 at 12 24 50 AM


On IOS, there is problem with the padding on top, and then the same problem we where having for the other picker on the session. There is a grey background on the picker which can't be removed. I think we can merge and fix on different PR

**Comment by whamester** [comment]
Screenshot 2024-07-10 at 8 51 08 AM

GoalPicker..tsx -> GoalPicker.tsx

**Comment by whamester** [comment]
Screenshot 2024-07-10 at 8 51 44 AM


I'll make some changes to fit the content to the screen

**Comment by whamester** [comment]
Screenshot 2024-07-10 at 9 51 17 AM

Screenshot 2024-07-10 at 9 52 15 AM

**Comment by whamester** [comment]
Figma ref: https://www.figma.com/design/PPygQ4sRjPUHr2hBe7aHxe/Updated-Mockups?node-id=11-2006&m=dev

**Review by whamester — APPROVED** [review]

**Pull request merged**
